### PR TITLE
[FIX] account_move_force_removal: buggy migration script

### PR DESCRIPTION
**Pull request by yajo**
Running the migration script fails with:

    AttributeError: 'psycopg2.extensions.cursor' object has no attribute 'ref'

@moduon

### CODE REVIEW

**Comment by yajo** [comment]
Please @pedrobaeza @angelgarciadelachica @AaronHForgeFlow @ValentinVinagre @HaraldPanten review the fix for this regression, introduced in https://github.com/OCA/account-financial-tools/pull/1386.

**Review by pedrobaeza — APPROVED** [review]

**Comment by yajo** [comment]
This should be fast-tracked IMHO.

**Review by etobella — APPROVED** [review]
nice catch

**Review by HaraldPanten — APPROVED** [review]
@pedrobaeza For me, you can merge this one.

I'm with Jairo, this one should be fast-tracked.

**Comment by HaraldPanten** [comment]
Hi Pedro, just a question to understand the "criteria"...

Why nobump instead of patch? 🤔

THX.

**Comment by pedrobaeza** [comment]
Because the migration script already has a past version, and this doesn't affect usual business logic.

**Comment by HaraldPanten** [comment]
> Because the migration script already has a past version, and this doesn't affect usual business logic.

Thanks Pedro 👍
